---
AllCops:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'Vagrantfile'
    - 'Policyfile.rb'
    - 'Berksfile'
    - 'Thorfile'
    - 'Gemfile'
    - 'metadata.rb'
    - 'test/**/*'
    - 'bin/**'
    - 'vendor/**/*'
    - 'airlift/**/*'
    - 'kitchen-zone/**/*'
Layout/LineLength:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Lint/SendWithMixinArgument:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
