name 'rc'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Library cookbook which provides a resource for writing runtime configuration files.'
long_description 'Library cookbook which provides a resource for writing runtime configuration files.'
version '1.5.2'

supports 'ubuntu'
supports 'centos'
supports 'redhat'
supports 'windows'
supports 'aix'
supports 'solaris'

depends 'poise', '~> 2.2'
